remove lang and make catapult group into folder

diff --git a/template/ios/project.yml b/template/ios/project.yml
--- a/template/ios/project.yml
+++ b/template/ios/project.yml
@@ -11,8 +11,28 @@ targets:
     scheme:
       testTargets:
         - CatapultTests
+    preBuildScripts:
+      - name: Start Packager
+        showEnvVars: false
+        script: |
+                export RCT_METRO_PORT="${RCT_METRO_PORT:=8081}"
+                echo "export RCT_METRO_PORT=${RCT_METRO_PORT}" > "${SRCROOT}/../node_modules/react-native/scripts/.packager.env"
+                if [ -z "${RCT_NO_LAUNCH_PACKAGER+xxx}" ] ; then
+                  if nc -w 5 -z localhost ${RCT_METRO_PORT} ; then
+                    if ! curl -s "http://localhost:${RCT_METRO_PORT}/status" | grep -q "packager-status:running" ; then
+                      echo "Port ${RCT_METRO_PORT} already in use, packager is either not running or not running correctly"
+                      exit 2
+                    fi
+                  else
+                    open "$SRCROOT/../node_modules/react-native/scripts/launchPackager.command" || echo "Can't start packager automatically"
+                  fi
+                fi
+    postBuildScripts:
+      - name: Bundle React Native code and images
+        script: |
+                export NODE_BINARY=node
+                ../node_modules/react-native/scripts/react-native-xcode.sh
   CatapultTests:
     type: bundle.unit-test
     platform: iOS
     sources: CatapultTests
-
